species.count <-read.csv("C://Users/Erik/Documents/GitHub/bark-beetle/data/masters_trees.csv")
species.count$spcode
sum(species.count$spcode=="PIPO" & species.count$mtn=="GM" & species.count$condition=="alive")
sum(species.count$spcode=="PIPO" & species.count$mtn=="DM" & species.count$condition=="alive")
sum(species.count$spcode=="PIAR" & species.count$mtn=="CM" & species.count$condition=="alive")
sum(species.count$spcode=="PICE" & species.count$mtn=="GM" & species.count$condition=="alive")
sum(species.count$spcode=="PICE" & species.count$mtn=="DM" & species.count$condition=="alive")
sum(species.count$spcode=="PIED" & species.count$mtn=="GM" & species.count$condition=="alive")
sum(species.count$spcode=="PIST3"& species.count$mtn=="GM" & species.count$condition=="alive")
sum(species.count$spcode=="PIST3"& species.count$mtn=="DM" & species.count$condition=="alive")
